language: node_js
node_js:
  - '0.10'
branches:
  except:
    - master
    - gh-pages
install: npm install
script: grunt
after-script: rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: VswSpDpl/xihNtPSN9OypzG1+4Tnl4fT4KHqDorgJYrnLTbaSlb4FZ+z8FvAwGSM1y9ZOh5IJEm8aduoYW43qW/RTJIa5xlmkHnj9Ji40WqdCj3IQsiuYR1USpNihUO3pIWU2PHgxGmYnTDVMVH6YpjHkGJIYdNHHmunMUt+IrQ=
  skip_cleanup: true
  app: picasahtml-dev
  on:
    repo: toshiya240/PicasaHtml
    branch: develop
