language: node_js
node_js:
  - "0.10"
branches:
  except:
    - master
    - gh-pages
install: npm install
script: grunt
deploy:
  provider: heroku
  api_key:
    secure: phXEVu7oldEDXPTp9n2UYpaLxTs66TCd6Vhy9KTnM9xF8AYyUCItQCWLJX6IIdu+nmjlPwmbFxQ1bdgypMSThU63bw6GnUYW1lgPCrTBLvRmT/R5mkF8hsuk3kold40bRWN0yplTZrpJlmAKLjDhxBdqEoirIfDa2Jj3lMcHTec=
  skip_cleanup: true
  app: picasahtml-dev
  on:
    repo: toshiya240/PicasaHtml
    branch: develop
